/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseIndexRouteImport } from './routes/browse.index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as DocumentIdRouteImport } from './routes/document.$id'
import { Route as BrowseSectionIdRouteImport } from './routes/browse.$sectionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSectionIdRoute = BrowseSectionIdRouteImport.update({
  id: '/$sectionId',
  path: '/$sectionId',
  getParentRoute: () => BrowseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/browse/$sectionId': typeof BrowseSectionIdRoute
  '/document/$id': typeof DocumentIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/browse/': typeof BrowseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/browse/$sectionId': typeof BrowseSectionIdRoute
  '/document/$id': typeof DocumentIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/browse': typeof BrowseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/browse/$sectionId': typeof BrowseSectionIdRoute
  '/document/$id': typeof DocumentIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/browse/': typeof BrowseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/login'
    | '/search'
    | '/settings'
    | '/browse/$sectionId'
    | '/document/$id'
    | '/login/callback'
    | '/browse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/settings'
    | '/browse/$sectionId'
    | '/document/$id'
    | '/login/callback'
    | '/browse'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/login'
    | '/search'
    | '/settings'
    | '/browse/$sectionId'
    | '/document/$id'
    | '/login/callback'
    | '/browse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  DocumentIdRoute: typeof DocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/document/$id': {
      id: '/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$sectionId': {
      id: '/browse/$sectionId'
      path: '/$sectionId'
      fullPath: '/browse/$sectionId'
      preLoaderRoute: typeof BrowseSectionIdRouteImport
      parentRoute: typeof BrowseRoute
    }
  }
}

interface BrowseRouteChildren {
  BrowseSectionIdRoute: typeof BrowseSectionIdRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseSectionIdRoute: BrowseSectionIdRoute,
  BrowseIndexRoute: BrowseIndexRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  DocumentIdRoute: DocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
